[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Messenger"
version = "0.0.1"
authors = [
    { name="Peter Davydov", email="dav.petia@yandex.ru" },
]
readme = "README.md"
requires-python = ">=3.12"
